/*
* this generated by
* get generate model on data/models with assets/models/university.json --skipProvider
* */
class University {
  int? id;
  UniversityInfo? universityInfo;
  String? createdAt;
  String? updatedAt;
  String? phoneNumber;
  String? profilePicture;
  String? profilePictureThumb;
  String? degree;
  String? firstName;
  String? lastName;
  String? email;
  String? invitationSent;
  String? invitationReceived;

  University(
      {this.id,
      this.universityInfo,
      this.createdAt,
      this.updatedAt,
      this.phoneNumber,
      this.profilePicture,
      this.profilePictureThumb,
      this.degree,
      this.firstName,
      this.lastName,
      this.email,
      this.invitationSent,
      this.invitationReceived});

  University.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    universityInfo = json['university_info'] != null
        ? UniversityInfo?.fromJson(json['university_info'])
        : null;
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    phoneNumber = json['phone_number'];
    profilePicture = json['profile_picture'];
    profilePictureThumb = json['profile_picture_thumb'];
    degree = json['degree'];
    firstName = json['first_name'];
    lastName = json['last_name'];
    email = json['email'];
    invitationSent = json['invitation_sent'];
    invitationReceived = json['invitation_received'];
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    if (universityInfo != null) {
      data['university_info'] = universityInfo!.toJson();
    }
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['phone_number'] = phoneNumber;
    data['profile_picture'] = profilePicture;
    data['profile_picture_thumb'] = profilePictureThumb;
    data['degree'] = degree;
    data['first_name'] = firstName;
    data['last_name'] = lastName;
    data['email'] = email;
    data['invitation_sent'] = invitationSent;
    data['invitation_received'] = invitationReceived;
    return data;
  }
}

class UniversityInfo {
  int? id;
  String? name;
  String? photo;

  UniversityInfo({this.id, this.name, this.photo});

  UniversityInfo.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    photo = json['photo'];
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['photo'] = photo;
    return data;
  }
}
